[package]
name = "configuration"
version = "0.5.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/configuration"
homepage = "https://github.com/stainless-steel/configuration"
documentation = "https://stainless-steel.github.io/configuration"
description = "The package provides a malleable tree structure."

[features]
default = ["toml"]
unstable = []

[dependencies]
options = "0.4"

[dependencies.toml]
version = "0.1"
optional = true
default-features = false
